### ISSUE TITLE
Error on less mixin

### ISSUE THREAD

**Issue by johnwp** [postcss/postcss-import#102]
I'm getting the following error when attempting to use a less mixin.  Is there a recommended workaround?  Should I just use SCSS instead?

```
ERROR in ./~/css-loader?sourceMap!./~/less-loader!./~/postcss-loader!./app/styles/app.less
postcss-import: /Users/johnwp/Repos/webapp/app/styles/bootstrap/mixins/hide-text.less:20:3: Unknown word
.text-hide() {
  .hide-text();
  ^
}
```

**Comment by jedmao** [comment]
You could always use [`postcss-mixins`](https://github.com/postcss/postcss-mixins) and define:

```css
@define-mixin hide-text {
    font: 0/0 serif;
    text-shadow: none;
    color: transparent;
}
```

And then:

```css
.foo {
    @mixin hide-text;
}
```
