### ISSUE TITLE
How to use resolve option for globbing

### ISSUE THREAD

**Issue by renestalder** [postcss/postcss-import#178]
Well, was a bit frustrated seeing globbing go in v8.0 of postcss-import. Thankfully you provided an example how to replace it with the resolve option and node-glob.

Anyway, after trying this, I couldn't get it working by now. Using the example of the v8 changelog, I can successfully resolve the absolute paths. But looking at the processed CSS file, the imports are just gone. They are not included and the import statements are missing.

Do I have to return an array with relative paths or what could be wrong?

As said, example from your changelog with node-glob.

```js
resolve: function (id, base) {
  var output = glob.sync(path.join(base, id))
  gutil.log(output)
  return output
}
```

**`postcss/_test-1.css`**
```css
:root {
  --postcss-test-1: green;
  --postcss-test-2: blue;
}
```

**`postcss/_test-2.css`**
```css
:root {
  --postcss-test-3: red;
  --postcss-test-4: yellow;
}
```

**`index.css`**
```css
@import 'postcss/*.css';

body {
  font-family: 'Helvetica Neue';
  background: #222;
  color: white;
}

.postcss {
  color: black;
}
```

Watching the logs, the paths get absolutely resolved and returned in an array.

```sh
[ '/Users/renestalder/whatwedo/Misc Cloned Repositories/craffft/src/postcss/_test-2.css',
  '/Users/renestalder/whatwedo/Misc Cloned Repositories/craffft/src/postcss/_test-1.css' ]
```

**Output `index.css`:**
```css
body {
  font-family: 'Helvetica Neue';
  background: #222;
  color: white;
}
.postcss {
  color: black;
}

/*# sourceMappingURL=index.css.map */
```

Any idea?
