### ISSUE TITLE
Play better with postcss-modules

### ISSUE THREAD

**Issue by longlho** [postcss/postcss-import#214]
If I stack those 2 together

```
require('postcss-import')(),
require('postcss-modules')()
```

variables.css

``` css
:root {
  --white: white;
  --black: black;
}
```

foo.css:

``` css
@import 'variables.css';
.foo {
  color: var(--white);
}
```

bar.css

``` css
@import 'variables.css';
.bar {
  composes: foo from 'foo.css';
  background-color: var(--black);
}
```

`postcss-modules`'s `composes` also inlines the file `foo`, so now I got an `@import` that's not at the top of the file, which violates the spec. The (broken) result is something like:

``` css
@import 'variables.css';
.foo {
  color: var(--white);
}
@import 'variables.css';
.bar {
  background-color: var(--black);
}
```

Any suggestion on how to address this issue? I'm not using `webpack` (just pure PostCSS). Do I have to write a plugin to dedupe & move imports up top?

Thanks!
