### ISSUE TITLE
Duplicate when importing

### ISSUE THREAD

**Issue by phzbox** [postcss/postcss-import#224]
Hi, I'm not sure if it's a bug or something I misunderstood.

With webpack, I import the same file in two different css files but it gets inlined twice.

```
A.css:
@import "core/cssutils.css";

B.css:
@import "core/cssutils.css";

core/cssutils.css:
body {
  font-family: verdana;
}

Webpack:
  postcss: function() {
    return [
      postcssImport
    ]
  },

Final result:
body{font-family:verdana}body{font-family:verdana}
```

**Comment by tonyxiao** [comment]
I'm seeing the same issue. @phzbox did you figure out a workaround?

**Comment by RyanZim** [comment]
@phzbox @tonyxiao Try the latest version, I suspect this issue is fixed.

**Comment by RyanZim** [comment]
Going to close this in a few days if I don't get a response.

**Comment by tomsapps** [comment]
bump for same issue

**Comment by RyanZim** [comment]
@tomsapps This issue should be fixed in v8.1.3 and later.

**Comment by bmenant** [comment]
@RyanZim I’m using v8.2.0 and I can reproduce the issue. Console log messages are also duplicated.

Or... could it be an erroneous webpack configuration?

```css
/* a.css */
@import "base.css";

/* b.css */
@import "base.css";

/* base.css */

:root {
  font-size: 1vmin;
}

h1 {
  /* pixrem module warns, since rem to pixel fallback with a dynamic root unit is not possible... */
  font-size: 1rem;
}
```

With this webpack config:

```js
    // Loaders...
    {
      test: /\.css$/,
      loader: extract('style-loader', [
        `css-loader?modules&localIdentName=${generateScopedName}&importLoaders=1`,
        'postcss-loader',
      ]),
    },
    // ...
  postcss: () => [
    atImport(),
    cssnext(),
  ],
```

The console outputs something like:

```    
Child extract-text-webpack-plugin:
    
    WARNING in ./~/css-loader?modules&localIdentName=[name]__[local]___[hash:base64:5]&importLoaders=1!./~/postcss-loader!./app/styles/base.css
    pixrem: Unit cannot be used for conversion, so 16px is used.

Child extract-text-webpack-plugin:
    
    WARNING in ./~/css-loader?modules&localIdentName=[name]__[local]___[hash:base64:5]&importLoaders=1!./~/postcss-loader!./app/styles/base.css
    pixrem: Unit cannot be used for conversion, so 16px is used.
    
```

And the extracted bundle.css:

```css
:root {
  font-size: 1vmin;
}
h1 { 
  /* pixrem module warns, since rem to pixel fallback with a dynamic root unit is not possible... */
  font-size: 16px;
  font-size: 1rem;
}
:root {
  font-size: 1vmin;
}
h1 {
  /* pixrem module warns, since rem to pixel fallback with a dynamic root unit is not possible... */
  font-size: 16px;
  font-size: 1rem;
}

```
