### ISSUE TITLE
Importing from node_modules and web_modules does not work when used with SugarSS parser

### ISSUE THREAD

**Issue by akella** [postcss/postcss-import#228]
Doing this in my sugar.sss file

``` sass
@import "normalize.css"
```

Having such a result:

``` css
body { {
  margin: 0;
}
}
```

Expected just to concatenate normalize into my file.
