### ISSUE TITLE
postcss-import add lines between classes and comments

### ISSUE THREAD

**Issue by alienlebarge** [postcss/postcss-import#229]
When I import files using postcss-import, it adds lines between class and comments.
For example when I `@import "normalize.css";` [here's what I get](https://gist.github.com/alienlebarge/baf91931b55d1d76128790030d29d755/4be470fcead38c2c83b8b7f3144699f453369a19):

``` css
/*! normalize.css v4.1.1 | MIT License | github.com/necolas/normalize.css */





/**
 * 1. Change the default font family in all browsers (opinionated).
 * 2. Correct the line height in all browsers.
 * 3. Prevent adjustments of font size after orientation changes in IE and iOS.
 */





html {
  font-family: sans-serif; /* 1 */
  line-height: 1.15; /* 2 */
  -ms-text-size-adjust: 100%; /* 3 */
  -webkit-text-size-adjust: 100%; /* 3 */
}





/**
 * Remove the margin in all browsers (opinionated).
 */
...
```

There's 5 lines between each comments and classes.
Here's how it might look like:

``` css
/*! normalize.css v4.1.1 | MIT License | github.com/necolas/normalize.css */

/**
 * 1. Change the default font family in all browsers (opinionated).
 * 2. Correct the line height in all browsers.
 * 3. Prevent adjustments of font size after orientation changes in IE and iOS.
 */

html {
  font-family: sans-serif; /* 1 */
  line-height: 1.15; /* 2 */
  -ms-text-size-adjust: 100%; /* 3 */
  -webkit-text-size-adjust: 100%; /* 3 */
}

/**
 * Remove the margin in all browsers (opinionated).
 */
...
```

Here's [the diff before & after postcss-import](https://gist.github.com/alienlebarge/baf91931b55d1d76128790030d29d755/revisions?diff=split).

Any idea how to fix that ?
