### ISSUE TITLE
Is there any way to configure this for alternate paths using config only settings in Webpack 4?

### ISSUE THREAD

**Issue by dschissler** [postcss/postcss-import#354]
I'm trying to put all of my dot configs into package.json and I'm having trouble with importing from all of the paths in my Webpack 4 `resolve.modules` paths.  I can import a vars.css from the local directory of a file but not from my theme directory.

Here is my `resolve.modules` section:

```
  resolve: {
    modules: [
      modulesDir,
      assetDir,
      vendorModulesDir,
    ],
  }
```

Here is my loader section:
```
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              importLoaders: 1,
            },
          },
          'postcss-loader',
        ],
```

Finally package.json:

```
  "postcss": {
    "plugins": {
      "postcss-preset-env": {
        "stage": 3
      },
      "postcss-import": {}
    }
  },
```

I'm trying to do this:

```css
@import 'theme/vars.css';
/* @import '~theme/vars.css'; */
/* @import './vars_local.css'; */

body {
  background-color: var(--submarine-color);
}
```

Then in my theme directory:

```css
:root {
  --submarine-color: yellow;
}
```

Is it possible to load from `modulesDir`, `assetDir` and `vendorModulesDir` without JS setup code (doing only in static configs)?
