### ISSUE TITLE
Feature Request: Add a nohoist option to allow inline imports

### ISSUE THREAD

**Issue by AndrewLeedham** [postcss/postcss-import#385]
### Feature
Would it be possible to add a `nohoist` option, so the `@import` statements would be replaced with the file contents in place. This comes into play when using the `filter` option, where the `@import` order is changed as non-filtered imports are hoisted to the top of the file.

### Use case
I am wanting to import inline CSS files in a SASS file before SASS processes the file. As importing CSS through SASS is deprecated.

### Example
```scss
// ------------------------
// before
//   file.css
* {
    box-sizing: border-box; 
}

//   style.scss
@import 'file.css';
@import 'file.scss';

// ------------------------
// after
//   style.scss
@import 'file.scss';
* {
    box-sizing: border-box; 
}

// ------------------------
// nohoist
//   style.scss
* {
    box-sizing: border-box; 
}
@import 'file.scss';
```
