### ISSUE TITLE
import-only files not in sourcemap

### ISSUE THREAD

**Issue by htho** [postcss/postcss-import#400]
I have file that has only @import rules, but nothing else.
This file can not be found in the sourcemap.
If I add a dummy comment, the file is in the sourcemap.

Maybe this is related to: #81?

I created a minimally working example:
https://github.com/htho/mwe-postcss-import-sourcemap-import-only

**Comment by RyanZim** [comment]
PR welcome to fix this.

**Comment by htho** [comment]
Puh.

I wouldn't even know where to start. I have no clue about the interaction between postcss and postcss-import.

**Comment by romainmenke** [comment]
> If I add a dummy comment, the file is in the sourcemap.

That is the only way to "fix" this.

`postcss-import` removes `@import` statements and anything that is imported will be coming from other files.

If a file contains only `@import` statements it will never be part of the source maps.

We could automatically add a comment with the `@import` statement as comment text :  
`/* @import "foo.css" */`

But any half decent minifier will scrub comments, re-introducing the issue.

-------

I am also unsure what the use case is.
Technically the file is missing from the source maps, but is this a problem?
Sourcemaps should still work for all other CSS.

If so, which problem?
Are there alternative solutions?

**Comment by romainmenke** [comment]
> We could automatically add a comment with the @import statement as comment text :
`/* @import "foo.css" */`

`esbuild` seems to do something like this.

`style.css` :
```css
@import url("a.css");
```

`a` :
```css
.box {
	background-color: green;
}
```


becomes :
```css
/* tests/001-core-features/001/default/a.css */
.box {
  background-color: green;
}

/* tests/001-core-features/001/default/style.css */
```
