### ISSUE TITLE
@charset matching issue in v14

### ISSUE THREAD

**Issue by AlecRust** [postcss/postcss-import#484]
If I use postcss-import [v14](https://github.com/postcss/postcss-import/releases/tag/14.0.0) I get the following warning:

```
postcss-import: @charset must precede all other statements
```

I see this was introduced in #447. Looks like my charsets aren't being merged in to one at the top.

Looking at my stylesheet, there are multiple charsets, but the only difference is the casing i.e.

```css
@charset "utf-8";

.blah {
  color: #5200d0;
}

@charset "UTF-8";

.blah {
  color: #5200d0;
}
```

I wonder if this should be handled by postcss-import i.e. including just one `@charset` at the top without an error?

Otherwise I'm not sure what the "fix" here is, these are 3rd party stylesheets being merged in to one.

**Comment by RyanZim** [comment]
Yeah, looking at this, it seems case doesn't matter in charset declarations, so we can probably merge them if that's the only difference. PR welcome.

**Comment by RyanZim** [comment]
OK, just re-reading this issue, want to make sure I'm not misunderstanding it. The example CSS you posted, is that your actual input CSS to postcss-import?

**Comment by AlecRust** [comment]
Actually looking now, this is the only charset I'm importing:

https://github.com/basecamp/trix/blob/b6c0047f87fa078aa65beb8ba297aba32ea4bcf1/dist/trix.css#L1

No matter where the Trix import is in my stylesheet:

```css
/*
 * Main application styles
 */

@import "trix";
@import "suitcss-base";
@import "suitcss-components-button";
@import "../styles/variables";
@import "../styles/base";
```
I get the same warning:
```sh
WARNING in ./app/packs/entrypoints/application.css (./app/packs/entrypoints/application.css.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[2].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./app/packs/entrypoints/application.css)
Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
Warning

(300:1) postcss-import: @charset must precede all other statements
 @ ./app/packs/entrypoints/application.css
```

If I remove the Trix import, I get no warning.

So there's just one uppercase charset in my stylesheet, coming from this 3rd party CSS.

I suppose expected behaviour is that this is automatically moved to the top. This seems to be what it's doing already (regardless of where the import is in the list).

Output:
```css
/*!*******************************************************************************************************************************************************************************************!*\
  !*** css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[2].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./app/packs/entrypoints/application.css ***!
  \*******************************************************************************************************************************************************************************************/
@charset "UTF-8";
/*
 * Main application styles
 */
/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */
/* Document
   ========================================================================== */
/**
 * 1. Correct the line height in all browsers.
 * 2. Prevent adjustments of font size after orientation changes in iOS.
 */
html {
  line-height: 1.15; /* 1 */
  -webkit-text-size-adjust: 100%; /* 2 */
}
```

So the output seems fine, but the error still occurs.
