### ISSUE TITLE
Ignore comments for "postcss-import: `@charset` must precede all other statements"

### ISSUE THREAD

**Issue by borisovcode** [postcss/postcss-import#549]
This is the buefy.css general file

```css
/*! Buefy v0.9.25 | MIT License | github.com/buefy/buefy */
@charset "UTF-8";
.is-noscroll {
  position: fixed;
  overflow-y: hidden;
  width: 100%;
  bottom: 0;
}
```

postcss-import generate module warning "postcss-import: `@charset` must precede all other statements"

May be ignore comments?
